#!/bin/sh
set -eu

replacements() {
  clang-format --output-replacements-xml "$@" | grep -c '</replacement>'
}

srcs=$(find . -type f -iname \*.h -o -iname \*.c)

if [[ $(replacements --style=file -i $srcs) != 0 ]]; then
  printf 'ERROR: There are formatting errors, please run `make format-c`.\n' 1>&2
  exit 1
fi
