#!/bin/sh
set -eu

DEBUG=${DEBUG:-false}
if $DEBUG; then
  set -x
fi

tmp=$(mktemp --tmpdir -d uplink-c-test-install.XXXXXXXXXX)
if ! $DEBUG; then
  trap "rm -fr '$tmp'" EXIT
fi

MAKE=${MAKE:-}

if [ -z "$MAKE" ]; then
    # Find GNU Make
    if hash gmake 2>/dev/null; then
        MAKE=gmake 
    elif hash make 2>/dev/null; then
        MAKE=make # Hope this one is GNU Make
    else
        echo "ERROR: No GNU Make found. Please install it." 2>&1
    fi
fi

export DESTDIR="$tmp/local"
$MAKE install

cd "$tmp"

cat > main.c <<EOF
#include <uplink/uplink.h>

int main() {
    return 0;
}
EOF

CFLAGS=${CFLAGS:--Wall -Werror -Wpedantic}
CC=${CC:-cc}


$CC $CFLAGS -DUPLINK_DISABLE_NAMESPACE_COMPAT main.c $(PKG_CONFIG_PATH=$DESTDIR/lib/pkgconfig pkg-config --cflags --libs libuplink) -o test-shared
LD_LIBRARY_PATH="$DESTDIR/lib" ./test-shared

$CC $CFLAGS -DUPLINK_DISABLE_NAMESPACE_COMPAT --static main.c $(PKG_CONFIG_PATH=$DESTDIR/lib/pkgconfig pkg-config --cflags --libs --static libuplink) -o test-static
./test-static
