#!/bin/sh
set -eu

version='0.0.0'

if git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]*' &>/dev/null; then
  version=$(git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]*')
fi

printf '%s\n' "${version/#v/}"
