#!/bin/sh
set -eu

version='0.0.0'

if [ $(git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]*' &>/dev/null) ]; then
  version=$(git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]*')
fi

if [ $(expr match "${version}" '^v') -eq 1 ]; then
  printf '%s\n' $(expr substr "${version}" 2 $(expr length "${version}"))
else
  printf '%s\n' "${version}"
fi
