name: Cross build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cross-build-no-darwin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [arm64, amd64, riscv, riscv64, loong64, ppc, ppcle, ppc64, ppc64le, mips, mipsle, misp64, wasm]
        goos: [js, linux, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Zig compiler
        uses: mlugg/setup-zig@v1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24.2'
      - name: Install make on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
        shell: powershell

      - name: Run make build
        env:
          GOARCH: ${{ matrix. goarch }}
          GOOS: ${{ matrix. goos }}
        run: make build
  cross-build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        # We could use the same list as the cross-build-no-darwin job, but we dropped the unusual
        # architectures to reduce checking time.
        goarch: [arm64, amd64, wasm]
        goos: [darwin, js, linux, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Zig compiler
        uses: mlugg/setup-zig@v1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24.2'
      - name: Install make on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
        shell: powershell

      - name: Run make build
        env:
          GOARCH: ${{ matrix. goarch }}
          GOOS: ${{ matrix. goos }}
        run: make build
